import badge from "./badge.png"
import expresso from "./expresso.png"
import bestprice from "./bestprice.png"
import cappuccino from "./cappuccino.png"
import chailattle from "./chailattle.png"
import coffeebeanIcon from "./coffeebean-icon.png"
import macchiato from "./macchiato.png"
import coffeeIcon from "./coffee-cup.png"
import coffeeBlastLeft from "./coffee_blast.png"
import coffeeBlastRight from "./coffee_blast-right.png"
import coffeeBean from "./coffeebean.png"
import coffeeBg from "./coffee-bg.png"
import cup from "./cup.png"

export { cup, badge, coffeeBg, expresso, bestprice, coffeeBean, cappuccino, chailattle, coffeebeanIcon, macchiato, coffeeIcon, coffeeBlastLeft, coffeeBlastRight }