import badge from "./badge.png"
import expresso from "./expresso.png"
import bestprice from "./best_price.png"
import cappuccino from "./cappuccino.png"
import chailattle from "./chailattle.png"
import coffeebeanIcon from "./coffeebean-icon.png"
import macchiato from "./macchiato.png"
import coffeeIcon from "./coffeecup.png"
import coffeeBlastLeft from "./coffee_blast.png"
import coffeeBlastRight from "./coffee_blast-right.png"
import coffeeBean from "./coffeebean.png"
import coffeeBg from "./coffeebg.png"
import cup from "./cup.png"
import beans from "./coffee_bean.png"

export { beans, cup, badge, coffeeBg, expresso, bestprice, coffeeBean, cappuccino, chailattle, coffeebeanIcon, macchiato, coffeeIcon, coffeeBlastLeft, coffeeBlastRight }